#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage:
  bootstrap_cloudfront_site.sh [options]

Options:
  --bucket <name>        S3 bucket name (default: code-atlas-<epoch>-<account>)
  --region <region>      S3 region (default: us-east-1)
  --config <path>        Output env file (default: deployment/cloudfront/site.env)
  --source-dir <path>    Source directory to publish (default: web/)
  --expected-text <txt>  Smoke-test marker text
  -h, --help             Show this help

This script creates:
1) S3 bucket
2) Public read bucket policy (for static site origin)
3) CloudFront distribution
4) Local config env file for future deploys
USAGE
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEFAULT_CONFIG="$ROOT_DIR/deployment/cloudfront/site.env"
REGION="us-east-1"
SOURCE_DIR="$ROOT_DIR/web"
EXPECTED_TEXT="vLLM-Spyre Integration Atlas"
CONFIG_PATH="$DEFAULT_CONFIG"
BUCKET_NAME=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bucket)
      BUCKET_NAME="$2"
      shift 2
      ;;
    --region)
      REGION="$2"
      shift 2
      ;;
    --config)
      CONFIG_PATH="$2"
      shift 2
      ;;
    --source-dir)
      SOURCE_DIR="$2"
      shift 2
      ;;
    --expected-text)
      EXPECTED_TEXT="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ! -d "$SOURCE_DIR" || ! -f "$SOURCE_DIR/index.html" ]]; then
  echo "Source directory must exist and include index.html: $SOURCE_DIR" >&2
  exit 1
fi

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"

if [[ -z "$BUCKET_NAME" ]]; then
  BUCKET_NAME="code-atlas-$(date +%s)-${ACCOUNT_ID}"
fi

echo "Using bucket: $BUCKET_NAME"
echo "Using region: $REGION"

if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
  echo "Bucket already exists: $BUCKET_NAME"
else
  if [[ "$REGION" == "us-east-1" ]]; then
    aws s3api create-bucket --bucket "$BUCKET_NAME" >/dev/null
  else
    aws s3api create-bucket \
      --bucket "$BUCKET_NAME" \
      --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=$REGION" >/dev/null
  fi
  echo "Created bucket: $BUCKET_NAME"
fi

aws s3api put-public-access-block \
  --bucket "$BUCKET_NAME" \
  --public-access-block-configuration \
"BlockPublicAcls=false,IgnorePublicAcls=false,BlockPublicPolicy=false,RestrictPublicBuckets=false"

cat > /tmp/code_atlas_bucket_policy.json <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "PublicReadGetObject",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::$BUCKET_NAME/*"
    }
  ]
}
POLICY

aws s3api put-bucket-policy \
  --bucket "$BUCKET_NAME" \
  --policy file:///tmp/code_atlas_bucket_policy.json

# Enable website hosting as fallback while CloudFront DNS propagates.
aws s3 website "s3://$BUCKET_NAME/" --index-document index.html

DIST_JSON="$(aws cloudfront create-distribution \
  --origin-domain-name "${BUCKET_NAME}.s3.amazonaws.com" \
  --default-root-object index.html)"

DISTRIBUTION_ID="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["Distribution"]["Id"])' <<< "$DIST_JSON")"
CLOUDFRONT_DOMAIN="$(python3 -c 'import json,sys; print(json.load(sys.stdin)["Distribution"]["DomainName"])' <<< "$DIST_JSON")"
S3_WEBSITE_URL="http://${BUCKET_NAME}.s3-website-${REGION}.amazonaws.com"

echo "Waiting for distribution to deploy (this can take several minutes)..."
aws cloudfront wait distribution-deployed --id "$DISTRIBUTION_ID"

mkdir -p "$(dirname "$CONFIG_PATH")"
cat > "$CONFIG_PATH" <<EOF
# Generated by bootstrap_cloudfront_site.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
AWS_REGION='$REGION'
BUCKET_NAME='$BUCKET_NAME'
DISTRIBUTION_ID='$DISTRIBUTION_ID'
CLOUDFRONT_DOMAIN='$CLOUDFRONT_DOMAIN'
SITE_URL='https://$CLOUDFRONT_DOMAIN'
S3_WEBSITE_URL='$S3_WEBSITE_URL'
SOURCE_DIR='$SOURCE_DIR'
EXPECTED_TEXT='$EXPECTED_TEXT'
EOF

echo "Saved config: $CONFIG_PATH"
echo "Distribution ID: $DISTRIBUTION_ID"
echo "CloudFront domain: $CLOUDFRONT_DOMAIN"
echo "Site URL: https://$CLOUDFRONT_DOMAIN"
echo "S3 fallback URL: $S3_WEBSITE_URL"
